"""Independent MQTT 3.1.1 byte fixtures; never generated by the SDK under test.

Field rules: https://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html
Sections 2.2.2-2.2.3, 3.1, 3.3 and 3.8. Platform randomness is fixed to 0x1234.
"""
import hashlib
import json


def publish(topic, payload, qos=2):
    variable = len(topic).to_bytes(2, "big") + topic + (b"\x12\x34" if qos else b"")
    remaining = len(variable) + len(payload)
    encoded = []
    while remaining:
        encoded.append(remaining & 127)
        remaining >>= 7
        if remaining:
            encoded[-1] |= 128
    return bytes([0x31 | (qos << 1), *(encoded or [0])]) + variable + payload


def write(directory):
    directory.mkdir(parents=True, exist_ok=True)
    fixtures = {
        "wire-connect": b"\x10\x16\x00\x04MQTT\x04\xc2\x00\x3c\x00\x04tab5\x00\x01u\x00\x01p",
        "wire-subscribe": b"\x82\x11\x12\x34\x00\x0csite/+/state\x02",
        "wire-publish-qos0": b"\x31\x08\x00\x03a/b\xc2\xb5Z",
        "wire-publish-qos1": b"\x33\x0a\x00\x03a/b\x12\x34\xc2\xb5Z",
        "wire-publish-qos2": b"\x35\x0a\x00\x03a/b\x12\x34\xc2\xb5Z",
        "wire-publish-empty": b"\x32\x07\x00\x03a/b\x12\x34",
        "wire-receive-empty": b"\x31\x0e\x00\x0cfixture/wire",
        "wire-receive-binary": b"\x33\x19\x00\x0cfixture/wire\x12\x34A\x00\r\n\t\x7f\xff\x80Z",
        "wire-receive-dup": b"\x3d\x19\x00\x0cfixture/wire\x12\x34A\x00\r\n\t\x7f\xff\x80Z",
        "wire-receive-zero-start": publish(b"t" * 1017, b"FIXTURE_RX_SECRET"),
        "wire-receive-fragments": publish(b"fixture/wire", b"FIXTURE_RX_SECRET" + b"x" * 1007),
        "wire-receive-home": publish(b"fixture/wire", b"FIXTURE_RX_SECRET"),
        "wire-receive-abandoned": publish(b"fixture/wire", b"FIXTURE_RX_SECRET"),
    }
    for name, data in fixtures.items():
        (directory / f"{name}.bin").write_bytes(data)
    (directory / "manifest.json").write_text(json.dumps({
        name: {"bytes": len(data), "sha256": hashlib.sha256(data).hexdigest()}
        for name, data in fixtures.items()
    }, indent=2) + "\n", encoding="utf-8")
