#pragma once
/* TCP-only native client. TLS/WS and device scheduling remain hardware checks. */
#define CONFIG_MQTT_PROTOCOL_311 1
#define CONFIG_MQTT_MSG_ID_INCREMENTAL 0
#define CONFIG_MQTT_TRANSPORT_SSL 0
#define CONFIG_MQTT_TRANSPORT_WEBSOCKET 0
#define CONFIG_MQTT_TRANSPORT_WEBSOCKET_SECURE 0
#define CONFIG_MQTT_SKIP_PUBLISH_IF_DISCONNECTED 0
#define CONFIG_MQTT_REPORT_DELETED_MESSAGES 0
#define CONFIG_MQTT_TASK_CORE_SELECTION_ENABLED 0
#define CONFIG_MQTT_EVENT_QUEUE_SIZE 1
